# Generated by Django 4.0.3 on 2022-09-05 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.FloatField()),
                ('depth', models.FloatField(default=0)),
                ('len', models.FloatField(default=None)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32646)),
            ],
            options={
                'verbose_name_plural': 'Casings',
            },
        ),
    ]
