# Generated by Django 4.0.3 on 2022-11-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_43',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_46',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_47',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_49',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_51',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_52',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_53',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_54',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_55',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_56',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_57',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_58',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_59',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_no_field_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_21',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_22',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_23',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_24',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_25',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_26',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_27',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_28',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_29',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_30',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_31',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_32',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_33',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_34',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_35',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_36',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_37',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_38',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_39',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_40',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_41',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_42',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_43',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_45',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_46',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_47',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_48',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_49',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_50',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_51',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_52',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_53',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_54',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_55',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_56',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_57',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_58',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_59',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='burner_type_60',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_21',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_22',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_23',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_24',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_25',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_26',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_27',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_28',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_29',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_30',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_31',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_32',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_33',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_34',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_35',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_36',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_37',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_38',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_39',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_40',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_41',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_42',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_43',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_45',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_46',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_47',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_48',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_49',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_50',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_51',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_52',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_53',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_54',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_55',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_56',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_57',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_58',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_59',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_id_60',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_20',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_21',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_22',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_23',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_24',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_25',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_26',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_27',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_28',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_29',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_30',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_31',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_32',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_33',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_34',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_35',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_36',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_37',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_38',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_39',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_40',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_41',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_42',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_43',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_44',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_45',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_46',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_47',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_48',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_49',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_50',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_51',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_52',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_53',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_54',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_55',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_56',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_57',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_58',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_59',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='customer_name_60',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_21',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_22',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_23',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_24',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_25',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_26',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_27',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_28',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_29',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_30',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_31',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_32',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_33',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_34',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_35',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_36',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_37',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_38',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_39',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_40',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_41',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_42',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_43',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_45',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_46',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_47',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_48',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_49',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_50',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_51',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_52',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_53',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_54',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_55',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_56',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_57',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_58',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_59',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='risershapemodel',
            name='status_60',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
